# Generated by Django 3.2.5 on 2021-07-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SZP', '0002_alter_user_vacations_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vacations_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
