# Generated by Django 3.2.5 on 2021-07-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SZP', '0003_alter_user_vacations_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('vendor', models.CharField(max_length=128)),
                ('serial_number', models.CharField(max_length=128)),
                ('power_consumption', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, 'odlewnicza'), (1, 'wózek widłowy'), (2, 'CNC')], default=-1)),
                ('orientation', models.IntegerField(choices=[(0, 'horyzontalna'), (1, 'wertykalna')], default=-1)),
                ('pressure', models.IntegerField()),
                ('pressure_tank', models.IntegerField()),
                ('technological_schema', models.BooleanField(default=True)),
            ],
        ),
    ]
