# Generated by Django 3.2.5 on 2021-07-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SZP', '0004_machines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furnace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('power_source', models.IntegerField(choices=[(0, 'gaz'), (1, 'prąd')], default='wybierz rodzaj zasilania')),
                ('machine', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='SZP.machines')),
            ],
        ),
    ]
