# Generated by Django 3.2.5 on 2021-07-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SZP', '0005_furnace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnace',
            name='power_source',
            field=models.IntegerField(choices=[(0, 'gaz'), (1, 'prąd')], default=-1),
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, 'hydroakumulator'), (1, 'akumulator tłokowy')], default=-1)),
                ('max_pressure', models.IntegerField()),
                ('work_pressure', models.IntegerField()),
                ('valve_setting_pressure', models.IntegerField()),
                ('serial_number', models.CharField(max_length=128)),
                ('UDT_number', models.CharField(max_length=128)),
                ('UDT_date', models.BooleanField(default=False)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SZP.machines')),
            ],
        ),
    ]
