# Generated by Django 3.2.5 on 2021-07-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SZP', '0008_alter_tank_udt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='UDT_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
