# Generated by Django 3.2.5 on 2021-07-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SZP', '0009_alter_tank_udt_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingMold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=128)),
                ('owner', models.CharField(max_length=128)),
                ('tool_shop', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TechSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_name', models.CharField(max_length=128)),
                ('alloy_type', models.IntegerField(choices=[(0, '226'), (1, '231'), (2, '230'), (3, 'ZL5')], default=-1)),
                ('pdf_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('casting_mold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SZP.castingmold')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SZP.machines')),
            ],
        ),
        migrations.AddField(
            model_name='castingmold',
            name='Machines',
            field=models.ManyToManyField(through='SZP.TechSchema', to='SZP.Machines'),
        ),
    ]
